# nginx proxy address - http://172.17.0.1:60134

name: tasks_md
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: baldissaramatheus/tasks.md:latest
    container_name: tasks-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      PGID: ${SERVICE_GROUP:-1000}
      PUID: ${SERVICE_USER:-1000}
      TITLE: ${APP_NAME:-My Tasks}
      LOCAL_IMAGES_CLEANUP_INTERVAL: ${LOCAL_IMAGES_CLEANUP_INTERVAL:-1440}
    ports:
      - '172.17.0.1:60134:8080'
    volumes:
      - './volumes/data/tasks:/tasks'
      - './volumes/config/tasks:/config'
    networks:
      - tasks_md

networks:
  tasks_md:
    name: tasks_md
    external: false
